var dicionario = {
  "classe"               : "class",
  "construtor"           : "constructor",
  "instância"            : "this",
  "método"               : "",
  "instanciar"           : "new",
  "função"               : "function",
  "retornar"             : "return",
  "variável"             : "var",
  "se"                   : "if",
  "ou então"             : "else if",
  "senão"                : "else",
  "verificar"            : "switch",
  "caso seja"            : "case",
  "em caso inesperado"   : "default",
  "parar"                : "break",
  "enquanto"             : "while",
  "imprimir"             : "console.log",
  "importar"             : "require",
  "nulo"                 : "null",
  "em_maiúsculo"         : "toUpperCase",
  "em_minúsculo"         : "toLowerCase",
  "verdadeiro"           : "true",
  "falso"                : "false",
};

module.exports = dicionario;